POST http://localhost:3000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer Cwh5Tulmw4BCmUzsPidqZNW1WjP6f25nCe94uz9aQ6IqQjpMRt

{
    "name": "product exemplo",
    "description": "Este é um exemplo de uma request feita pelo rest client no vscode",
    "price": 120.00,
    "stock": 10
}