POST http://localhost:3000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0aGFkZXUiLCJpYXQiOjE3NDQ2NTE4MTQsImV4cCI6MTc0NDY1NTQxNH0.9iDl-GtFwuGjQIe_eLVoMUMXJ4cf3Cs2cQyHhEbH_R8

{
    "name": "product exemplo",
    "description": "Este é um exemplo de uma request feita pelo rest client no vscode",
    "price": 120.00,
    "stock": 10
}