PATCH http://localhost:3000/products/1/sell HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0aGFkZXUiLCJpYXQiOjE3NDQ2NTE4MTQsImV4cCI6MTc0NDY1NTQxNH0.9iDl-GtFwuGjQIe_eLVoMUMXJ4cf3Cs2cQyHhEbH_R8

{
  "quantity": 3
}